### PR TITLE
Fix syntax errors

### PR DESCRIPTION
**Pull request by robindevitt**
This PR fixes some syntax errors that have been reported on.

>PHP Parse error: syntax error, unexpected ')' in dev-tools-command/inc/command/class-command.php on line 817

### CODE REVIEW

**Comment by joehoyle** [comment]
@robindevitt this error is due to a too old version of PHP (>7.4), but I don't think we support < 7.4 in the latest version of Altis, so I'm not sure why would need to do this (unless someone is erroneously using PHP 7.2 with the latest version of Altis).

**Comment by robindevitt** [comment]
@joehoyle It's for a scenario where a user is currently upgrading from Altis Upgrading from v5 to v11 and they are making use of `composer server cli -- altis migrate`

**Comment by joehoyle** [comment]
@robindevitt hmm ok, I don't think this would be the _only_ place though to support that, it would effectively mean that we need to make sure all of Altis is still compatible with PHP 7.2, which it is not. 

`altis migrate` should be run _after_ `composer update`, and restarting `local-server` no? In which case it _should_ be running PHP 7.4 already. I could be wrong, but this sounds like user-error on doing the local-server upgrade if somehow they are not running PHP 7.4 when running `altis migrate`.

**Comment by joehoyle** [comment]
Oh actually, also this would have to do with what version of PHP people had installed locally (not local-server, apoliogies). In which case the next question: when we moved to PHP 7.4 only, did we stipulate that users must also upgrade their host machine's version of PHP?

**Comment by robindevitt** [comment]
Closing this ticket as the reported issue came through a local environment with a potentially older version of php installed causing the errors. Where as they should be using PHP 7.4+.

**Pull request closed without merging**
