### PR TITLE
Use multisite-install command as db populator cmd

### PR DESCRIPTION
**Pull request by roborourke**
An option to consider for setting up tests. Has the advantage of triggering Altis setup routines like EP indexing. No search / replace required either.

### CODE REVIEW

**Comment by roborourke** [comment]
@shadyvb I'll leave it up to you to merge this but wanted to put it forward as an option. Let me know what you think. I really couldn't find a suitable way around the issue I was seeing with indexing getting into a loop when tests might have multiple queries / invocations of the app.

**Comment by shadyvb** [comment]
@roborourke tbh I hate having to import a dump anyways, if we can make the install work without too much added time, I'd actually prefer it.

**Comment by roborourke** [comment]
This is working ok for me

**Review by shadyvb — APPROVED** [review]

**Comment by shadyvb** [comment]
It works for me, a bit slower, but works. Having some issue with tests taking too long to start executing, unsure if it is related, digging deeper.

**Comment by roborourke** [comment]
Could try adding the `--debug` option to the WP CLI command and then `-- -vvv` to your codecept command. The initial test takes a while to get going but then subsequent tests are quicker.

Which tests are you running? I'm using mutagen for the file mounting so we could benchmark it to some extent.

I'd also check the php server logs - if you see tons of requests to ES like 404 `index_exists` then you might need to check the change I did to prevent ES indexing on wp-browser requests.

**Comment by shadyvb** [comment]
Testing with this branch things seem to be fine, i'll merge this and track what's causing the issue from the other changes.

**Pull request merged**
